export const starterDishesDishes = [{
    "Category": "Starters",
    "Name": "Antipasti Misti",
    "image": "img/st_01.jpg",
    "Description": "Italian starters platter with cold vegetables and various sauces",
    "Allergen": "Contains milk and products thereof (including lactose)",
    "Brutto": 12.00,
    "Quote": 10,
    "Tax": 1.09,
    "Net": 10.91,
    "Age": false,
    "Rate": true
}
,{
    "Category": "Starters",
    "Name": "Mozzarella con Pomodoro",
    "image": "img/st_02.jpg",
    "Description": "with mozzarella, tomato slices, basil and olive oil",
    "Allergen": "Contains milk and products thereof (including lactose)",
    "Brutto": 8.40,
    "Quote": 10,
    "Tax": 0.76,
    "Net": 7.64,
    "Age": false,
    "Rate": true
},{
    "Category": "Starters",
    "Name": "Melanzane alla Bolognese",
    "image": "img/st_03.jpg",
    "Description": "with tomatoes, meat sauce and mozzarella gratin",
    "Allergen": "Contains milk and products thereof (including lactose)",
    "Brutto": 9.00,
    "Quote": 10,
    "Tax": 0.82,
    "Net": 8.18,
    "Age": false,
    "Rate": true
},{
    "Category": "Starters",
    "Name": "Broccoli con Prosciutto",
    "image": "img/st_04.jpg",
    "Description": "with ham and mozzarella gratin",
    "Allergen": "a, b, c, d",
    "Brutto": 9.50,
    "Quote": 10,
    "Tax": 0.86,
    "Net": 8.64,
    "Age": false,
    "Rate": true
},{
    "Category": "Starters",
    "Name": "Insalata al Tonno",
    "image": "img/st_05.jpg",
    "Description": "mixed salad with tuna and olive oil. Choice of: with American dressing, with balsamic oil dressing, with garlic dressing, with yogurt dressing or without dressing.",
    "Allergen": "a, b, c, d",
    "Brutto": 9.50,
    "Quote": 10,
    "Tax": 0.86,
    "Net": 8.64,
    "Age": false,
    "Rate": true
},{
    "Category": "Starters",
    "Name": "Breaded Onion Rings",
    "image": "img/st_06.jpg",
    "Description": "with tartare sauce",
    "Allergen": "a, b, c, d",
    "Brutto": 9.50,
    "Quote": 10,
    "Tax": 0.86,
    "Net": 8.64,
    "Age": false,
    "Rate": true
}
]
export const mainDishes = [{
    "Category": "Main Dishes",
    "SubCat": "Pasta",
    "Name": "Pasta di Formaggi",
    "image": "img/m_p_01.jpg",
    "Description": "with 4 cheeses in cream sauce Choice of: Gnocchi, Penne, Spaghetti, Tagliatelle or Tortellini.",
    "Allergen": "Contains cereals and products thereof containing gluten Contains eggs and products thereof Contains milk and products thereof (including lactose)",
    "Brutto": 9.40,
    "Quote": 10,
    "Tax": 0.91,
    "Net": 9.09,
    "Age": false,
    "Rate": true
},{
    "Category": "Main Dishes",
    "SubCat": "Pasta",
    "Name": "Pasta di Funghi",
    "image": "img/m_p_02.jpg",
    "Description": "with mushrooms in cream sauce Choice of: Gnocchi, Penne, Spaghetti, Tagliatelle or Tortellini.",
    "Allergen": "Contains cereals and products thereof containing gluten Contains eggs and products thereof Contains milk and products thereof (including lactose)",
    "Brutto": 9.40,
    "Quote": 10,
    "Tax": 0.85,
    "Net": 8.55,
    "Age": false,
    "Rate": true
},{
    "Category": "Main Dishes",
    "SubCat": "Pasta",
    "Name": "Pasta Carbonara",
    "image": "img/m_p_03.jpg",
    "Description": "with bacon, ham and cream Choice of: Gnocchi, Penne, Spaghetti, Tagliatelle or Tortellini.",
    "Allergen": "a, b, c",
    "Brutto": 9.40,
    "Quote": 10,
    "Tax": 0.85,
    "Net": 8.55,
    "Age": false,
    "Rate": true
},{
    "Category": "Main Dishes",
    "SubCat": "Pasta",
    "Name": "Pasta alla Bolognese",
    "image": "img/m_p_04.jpg",
    "Description": "with meat sauce Choice of: Gnocchi, Penne, Spaghetti, Tagliatelle or Tortellini.",
    "Allergen": "a, b, c",
    "Brutto": 9.40,
    "Quote": 10,
    "Tax": 0.85,
    "Net": 8.55,
    "Age": false,
    "Rate": true
},{
    "Category": "Main Dishes",
    "SubCat": "Pasta",
    "Name": "Pasta Gorgonzola",
    "image": "img/m_p_05.jpg",
    "Description": "with Gorgonzola sauce Choice of: Gnocchi, Penne, Spaghetti, Tagliatelle or Tortellini.",
    "Allergen": "a, b, c",
    "Brutto": 9.40,
    "Quote": 10,
    "Tax": 0.85,
    "Net": 8.55,
    "Age": false,
    "Rate": true
},{
    "Category": "Main Dishes",
    "SubCat": "Pasta",
    "Name": "Pasta Spinaci",
    "image": "img/m_p_06.jpg",
    "Description": "with spinach sauce Choice of: Gnocchi, Penne, Spaghetti, Tagliatelle or Tortellini.",
    "Allergen": "a, b, c",
    "Brutto": 9.40,
    "Quote": 10,
    "Tax": 0.85,
    "Net": 8.55,
    "Age": false,
    "Rate": true
},{
    "Category": "Main Dishes",
    "SubCat": "Pizza",
    "Name": "Pizza Siciliana",
    "image": "img/m_p_01.jpg",
    "Description": "with olives, capers and anchovies. Pizza from the Wood-Fired Oven Ø 33cm. All pizzas are prepared with tomato sauce and cheese.",
    "Allergen": "Contains cereals and products thereof containing gluten Contains fish and products thereof Contains milk and products thereof (including lactose) Contains sulphur dioxide and sulphites",
    "Brutto": 9.60,
    "Quote": 10,
    "Tax": 0.87,
    "Net": 8.73,
    "Age": false,
    "Rate": true
},{ 
    "Category": "Main Dishes",
    "SubCat": "Pizza",
    "Name": "Pizza Caprese",
    "image": "img/m_z_02.jpg",
    "Description": "with mozzarella, basil and fresh tomatoes. Pizza from the Wood-Fired Oven Ø 33cm. All pizzas are prepared with tomato sauce and cheese.",
    "Allergen": "Contains cereals and products thereof containing gluten Contains milk and products thereof (including lactose)",
    "Brutto": 9.60,
    "Quote": 10,
    "Tax": 0.87,
    "Net": 8.73,
    "Age": false,
    "Rate": true
},{
    "Category": "Main Dishes",
    "SubCat": "Pizza",
    "Name": "Pizza Romana",
    "image": "img/m_z_03.jpg",
    "Description": "with anchovies. Pizza from the Wood-Fired Oven Ø 33cm. All pizzas are prepared with tomato sauce and cheese.",
    "Allergen": "Contains cereals and products thereof containing gluten Contains fish and products thereof Contains milk and products thereof (including lactose) Contains sulphur dioxide and sulphites",
    "Brutto": 9.60,
    "Quote": 10,
    "Tax": 0.87,
    "Net": 8.73,
    "Age": false,
    "Rate": true
},{
    "Category": "Main Dishes",
    "SubCat": "Pizza",
    "Name": "Pizza Salami",
    "image": "img/m_z_04.jpg",
    "Description": "with salami. Pizza from the Wood-Fired Oven Ø 33cm. All pizzas are prepared with tomato sauce and cheese.",
    "Allergen": "Contains cereals and products thereof containing gluten Contains fish and products thereof Contains milk and products thereof (including lactose) Contains sulphur dioxide and sulphites",
    "Brutto": 9.60,
    "Quote": 10,
    "Tax": 0.87,
    "Net": 8.73,
    "Age": false,
    "Rate": true
},{
    "Category": "Main Dishes",
    "SubCat": "Pizza",
    "Name": "Pizza Cardinale",
    "image": "img/m_z_05.jpg",
    "Description": "with ham. Pizza from the Wood-Fired Oven Ø 33cm. All pizzas are prepared with tomato sauce and cheese.",
    "Allergen": "Contains cereals and products thereof containing gluten Contains fish and products thereof Contains milk and products thereof (including lactose) Contains sulphur dioxide and sulphites",
    "Brutto": 9.60,
    "Quote": 10,
    "Tax": 0.87,
    "Net": 8.73,
    "Age": false,
    "Rate": true
},{
    "Category": "Main Dishes",
    "SubCat": "Pizza",
    "Name": "Pizza alla Regina",
    "image": "img/m_z_06.jpg",
    "Description": "with ham and mushrooms. Pizza from the Wood-Fired Oven Ø 33cm. All pizzas are prepared with tomato sauce and cheese.",
    "Allergen": "Contains cereals and products thereof containing gluten Contains fish and products thereof Contains milk and products thereof (including lactose) Contains sulphur dioxide and sulphites",
    "Brutto": 9.60,
    "Quote": 10,
    "Tax": 0.87,
    "Net": 8.73,
    "Age": false,
    "Rate": true
}
];
export const dessertDishes = [
    {
    "Category": "Desserts",
    "Name": "Tiramisu",
    "image": "img/d_01.jpg",
    "Description": "homemade",
    "Allergen": "a, n, h, k",
    "Brutto": 5.50,
    "Quote": 10,
    "Tax": 5.00,
    "Net": 0.5,
    "Age": false,
    "Rate": true
},{
    "Category": "Desserts",
    "Name": "Profiteroles",
    "image": "img/d_02.jpg",
    "Description": "cream puffs filled with vanilla cream",
    "Allergen": "Contains cereals and products thereof containing gluten Contains eggs and products thereof Contains milk and products thereof (including lactose)",
    "Brutto": 5.00,
    "Quote": 10,
    "Tax": 0.45,
    "Net": 4.55,
    "Age": false,
    "Rate": true
},{
    "Category": "Desserts",
    "Name": "Chocolate Nut Pancake",
    "image": "img/d_03.jpg",
    "Description": "",
    "Allergen": "Contains cereals and products thereof containing gluten Contains eggs and products thereof Contains milk and products thereof (including lactose) Contains nuts and products thereof",
    "Brutto": 5.00,
    "Quote": 10,
    "Tax": 0.45,
    "Net": 4.55,
    "Age": false,
    "Rate": true
},{
    "Category": "Desserts",
    "Name": "Breaded Apple Slices",
    "image": "img/d_04.jpg",
    "Description": "with chocolate sauce and whipped cream",
    "Allergen": "Contains cereals and products thereof containing gluten Contains eggs and products thereof",
    "Brutto": 5.00,
    "Quote": 10,
    "Tax": 0.45,
    "Net": 4.55,
    "Age": false,
    "Rate": true
}
]
export const beverageDishes = [
{
    "Category": "Beverage",
    "SubCat": "Alc",
    "Name": "Merlot 0,75l",
    "image": "img/b_01.jpg",
    "Description": "red wine, 10,00 vol, 12,67 €/l, 750ml.",
    "Allergen": "Contains sulphur dioxide and sulphites",
    "Brutto": 9.50,
    "Quote": 20,
    "Tax": 1.58,
    "Net": 7.92,
    "Age": true,
    "Rate": true
},{
    "Category": "Beverage",
    "SubCat": "Alc",
    "Name": "Beer 0,5l",
    "image": "img/b_02.jpg",
    "Description": "home brand, 5,00 vol, 6,00 €/l, 500ml.",
    "Allergen": "Contains cereals and products thereof containing gluten",
    "Brutto": 3.00,
    "Quote": 20,
    "Tax": 0.5,
    "Net": 2.5,
    "Age": true,
    "Rate": true
},{
    "Category": "Beverage",
    "SubCat": "Alc",
    "Name": "Jägermeister 0,02l",
    "image": "img/b_03.jpg",
    "Description": "35,0 vol, 175,00 €/l, 20ml.",
    "Allergen": "-",
    "Brutto": 3.00,
    "Quote": 20,
    "Tax": 0.5,
    "Net": 2.5,
    "Age": true,
    "Rate": true
},{ 
    "Category": "Beverage",
    "SubCat": "Non",
    "Name": "Coca Cola 0,33l can",
    "image": "img/b_n_04.jpg",
    "Description": "Coca Cola Original is and remains the classic among soft drinks. The tried-and-tested recipe convinces with its special taste, which makes every moment a pleasure. Contains caffeine (10,00 mg/100 ml), 6,67 €/l, 330ml",
    "Allergen": ["Substances or products causing allergies or intolerances", "With colorant", "contains acidifiers", "Contains caffeine", "LMIV - Allergen", "almonds", "Contains nuts and products thereof", "cashews", "hazelnuts", "macadamia", "Brazil nuts", "pecan nuts", "pistachio nuts", "Queensland nuts", "walnuts", "Nutrition facts", "Ingredentis:", "Wasser, Zucker, Kohlendioxid, Farbstoff E 150d, Säuerungsmittel E 338, natürliche Aromen inklusive Koffein","Nährwerte pro 100ml:", "KJ : 180", "Kcal : 42", "Fett : 0g", "davon gesättigte Fettsäuren : 0g", "Kohlenhydrate : 10,6g", "Zucker : 10,6g", "Eiweiß : 0g", "Salz : 0g"],
    "Brutto": 2.20,
    "Quote": 10,
    "Tax": 0.20,
    "Net": 2.00,
    "Age": true,
    "Rate": false
}
];

export interface IDishes {
    Category: string,
    SubCat?: string,
    Name: string,
    image: string,
    Description: string,
    Brutto: number,
    Quote: number,
    Tax: number,
    Net: number,
    Age: boolean,
    Rate: boolean
};